# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy necessary files first
COPY package*.json tsconfig.json ./
# Install dependencies without running postinstall scripts
RUN npm install --ignore-scripts

# Copy entire repository
COPY . .
# Build the TypeScript source
RUN npm run build

FROM node:lts-alpine AS runner
WORKDIR /app

# Copy package manifests
COPY --from=builder /app/package*.json ./
# Install production dependencies without running postinstall
RUN npm install --production --ignore-scripts

# Copy build artifacts
COPY --from=builder /app/dist ./dist

# Default environment
ENV TRANSPORT_MODE=http
EXPOSE 3000

CMD ["node", "dist/index.js"]
